### ISSUE TITLE
GH Issue Project sync is broken

### ISSUE THREAD

**Issue by AbhiPrasad** [getsentry/team-webplatform-meta#10]

**Comment by AbhiPrasad** [comment]
https://github.com/orgs/getsentry/projects/31/workflows/query_matched_add_project_item might help us (if it allows us through)

**Comment by HazAT** [comment]
Something changed in the Github GraphQL API which broke our GH Action sync
See: https://github.com/getsentry/sentry-project-automation/actions/runs/3984926135/jobs/6831690475

It seems `projectNext` got renamed to `projectV2`
https://github.com/getsentry/sentry-project-automation/commit/dfb8baa80ecda1a0f4736416597232b4a8b6c9f0

and now it can't find the `title`
> Field 'title' doesn't exist on type 'ProjectV2Item'
see the run action.

We need to fix this, I didn't have time to drill in much deeper cause of meetings :/

**Comment by HazAT** [comment]
OK closing, sync should work again
