### ISSUE TITLE
404 Requests Parameterization

### ISSUE THREAD

**Issue by smeubank** [getsentry/team-webplatform-meta#20]
### Problem:
Since fixes have been delivered for parameterization of the transactions that went into the <> unparameterized bucket. It has called to attention that 404 requests are appearing as pure URLs. This 1 not useful and 2 against our best practices for instrumentation. The SDK should provide the best txn name possible, not the URL, 

### Goal:
SDKs should "name" transactions for 404s as 404 or likewise. There is a route and the SDK cannot necessarily parameterize them.

"404 not found" for example as name.

_Question?_
If the SDKs can begins flagging these 404s what is the best way to display them in UI?

**Comment by smeubank** [comment]
@antonpirker or @AbhiPrasad pure opinion stuff no fire. This came up in a thread with Bruno and I want to discuss with Albert, how they would like display these 404s in the product. But if you either of you have a strong opinion I would be happy to hear it.

Created this after a chat with Jan for context

**Comment by AbhiPrasad** [comment]
If something is a 404 transaction - we should be setting a span status that is 404, perhaps we can take advantage of that?
