### ISSUE TITLE
Source Maps Debug Id V0 Test Run

### ISSUE THREAD

**Issue by lforst** [getsentry/team-webplatform-meta#35]
#### 1

- Apply CLI to CRA project - check output
- Upload artifacts
- Throw error - check if correctly source mapped

#### 2

- Apply CLI to Next.js project - check output
- Upload artifacts
- Throw error clientside - check if correctly source mapped
- Throw error serverside - check if correctly source mapped

#### 3

- Apply CLI to subset of Next.js project - check output
- Upload artifacts
- Throw error clientside - check if individual frames are correctly source mapped
- Throw error serverside - check if individual frames are correctly source mapped

**Comment by Jesse-Box** [comment]
@lforst can you close this ticket
