### ISSUE TITLE
Simplify Tokens for CI 

### ISSUE THREAD

**Issue by smeubank** [getsentry/team-webplatform-meta#67]
An expansion on the "[Order of Execution](https://github.com/getsentry/rfcs/blob/feature/upload-tokens/text/0091-ci-upload-tokens.md#order-of-execution)" from RFC CI Upload Tokens

1. The most important piece is the new token. As it behaves like any other token there is no immediate necessity for a tool to add support for structural tokens.
2. Add a user interface to issue these new tokens on an org level.
3. Add a user interface to issue these new tokens right from the documentation.
4. Add support for structural tokens to sentry-cli to allow org and project to be made optional.
5. Change documentation to no longer show org and project for tool config.

```[tasklist]
### Server side (sentry)
- [ ] Need to agree on token format
- [ ] define API for FE and Docs to use - ideally generic so the work in other places could start
- [ ] Able to generate new tokens, store, and authenticate based upon
- [ ] Test forwards and backwards compatibility
```

```[tasklist]
### UI (Docs/onboarding)
- [ ] feature flag to dev behind - work can start prior to above
- [ ] Sentry UI to fetch fetch new token
- [ ] Org and project can still be there with option of removing them later (cli can continue to accept and send)
- [ ] Consider hybrid cloud, single tenant, and self hosted
```

```[tasklist]
### sentry-cli
- [ ] Auth required
- [ ] Org and project can still be required with option of setting them to optional later
```

```[tasklist]
### Wizard
- [ ] wouldn’t need to move to new method right away
- [ ] But could eventually just set the new one once the cli has them as optional
```

**Comment by stephanie-anderson** [comment]
Will close this issue due to new epic issue
