### ISSUE TITLE
The perfect* SDK

### ISSUE THREAD

**Issue by HazAT** [getsentry/team-webplatform-meta#89]
# Goals
- Have a mock implemented SDK that covers most important top-level APIs of our SDKs
(`captureX`, `addBreadcrumb`, `setContext`, `startSpan` ...)
- The mock should be able to run but not send anything
- It should be possible to test the mock in different scenarios -> Async calls, Requests context, other context manager related scenarios
- Be able to interact with an OTEL SDK in an "enhancing way", meaning it should be possible to setup a OTEL SDK and spans created there should show up in the output of the mock

# Non-Goals:
- Have a fully functioning SDK

**Comment by stephanie-anderson** [comment]
https://www.notion.so/sentry/Performance-simplified-59c8872f1173439b97386f14dd0ea0c6

**Comment by HazAT** [comment]
We decided to stop pursuing this for now - we know our internal shortcomings and what the top-level SDK API should look like.
Since this always was considered an internal prototype we can move on.
